version: "3.9"

services:
  db:
    image: mysql:5.7
    ports:
      - 8083:3306
    volumes:
      - $PWD/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Word@500
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: Word@500

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - $PWD/wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: Word@500
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wordpress_data: {}

